#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t aiida \
                         -C "start_jupyter -T @tool -t aiida.ipynb" \
                         -u anaconda-7 \
                         -r none \
                         -w headless
